### ISSUE TITLE
[Bug] NameError: name 'xxxxxxx' is not defined

### ISSUE THREAD

**Issue by sjedlick** [telekom-mms/trivy-dojo-report-operator#28] opened 2023-11-14 12:33 UTC
### Description

There are various error messages in log:
```
[2023-11-14 11:55:41,120] kopf.objects         [INFO    ] [obiwan/statefulset-solr-leader-solr] Working on statefulset-solr-leader-solr
[2023-11-14 11:55:41,122] kopf.objects         [ERROR   ] [obiwan/statefulset-solr-leader-solr] Handler 'send_to_dojo' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/kopf/_core/actions/execution.py", line 276, in execute_handler_once
    result = await invoke_handler(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kopf/_core/actions/execution.py", line 371, in invoke_handler
    result = await invocation.invoke(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke
    await asyncio.shield(future)  # slightly expensive: creates tasks
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<decorator-gen-1>", line 2, in send_to_dojo
  File "/usr/local/lib/python3.11/site-packages/prometheus_client/context_managers.py", line 80, in wrapped
    return func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/src/handlers.py", line 79, in send_to_dojo
    settings.DEFECT_DOJO_PRODUCT_NAME = eval(settings.DEFECT_DOJO_PRODUCT_NAME)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'defectdojo' is not defined

```

    
Helm values looks like this:
```
account:
  serviceAccount:
    annotations: {}
defectDojoApiCredentials:
  apiKey: "${DEFECT_DOJO_API_KEY}"
  url: "${DEFECT_DOJO_URL}"
operator:
  replicas: 1
  trivyDojoReportOperator:
    env:
      defectDojoActive: "true"
      defectDojoAutoCreateContext: "true"
      defectDojoCloseOldFindings: "false"
      defectDojoCloseOldFindingsProductScope: "false"
      defectDojoDeduplicationOnEngagement: "true"
      defectDojoMinimumSeverity: Info
      defectDojoProductTypeName: Research and Development
      defectDojoPushToJira: "false"
      defectDojoTestTitle: Kubernetes
      defectDojoVerified: "false"
      defectDojoEngagementName: "operator"
      defectDojoProductName: body["report"]["artifact"]["repository"]
      defectDojoEvalProductName: "true"
    image:
      repository: ghcr.io/telekom-mms/docker-trivy-dojo-operator
      tag: trivy-dojo-report-operator-0.3.3
```
 

### Reproduction steps

with start of the pod these errors are in the log

### Current Behavior

- error messages like in the issue description
- no data is sent to defectdojo

### Expected Behavior

- data is sent to defectdojo without any errors

**Comment by szEvEz** [comment] 2023-11-14 14:48
I was able to reproduce the issue.

```sh
2023-11-14 15:47:21,068] kopf.objects         [ERROR   ] [default/pod-lol23-lol23] Handler 'send_to_dojo' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/home/josz/.cache/pypoetry/virtualenvs/trivy-dojo-report-operator-qppFTy45-py3.10/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 276, in execute_handler_once
    result = await invoke_handler(
  File "/home/josz/.cache/pypoetry/virtualenvs/trivy-dojo-report-operator-qppFTy45-py3.10/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 371, in invoke_handler
    result = await invocation.invoke(
  File "/home/josz/.cache/pypoetry/virtualenvs/trivy-dojo-report-operator-qppFTy45-py3.10/lib/python3.10/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke
    await asyncio.shield(future)  # slightly expensive: creates tasks
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "<decorator-gen-1>", line 2, in send_to_dojo
  File "/home/josz/.cache/pypoetry/virtualenvs/trivy-dojo-report-operator-qppFTy45-py3.10/lib/python3.10/site-packages/prometheus_client/context_managers.py", line 80, in wrapped
    return func(*args, **kwargs)
  File "/home/josz/workspace/github/trivy-dojo-report-operator/src/handlers.py", line 80, in send_to_dojo
    settings.DEFECT_DOJO_PRODUCT_NAME = eval(settings.DEFECT_DOJO_PRODUCT_NAME)
  File "<string>", line 1, in <module>
NameError: name 'report' is not defined
```

Looks like `report` is not evaluated properly?

I've put the value of `defectDojoProductName` in single quotes, resulting in the following complete config

```yaml
account:
  serviceAccount:
    annotations: {}
defectDojoApiCredentials:
  apiKey: "${DEFECT_DOJO_API_KEY}"
  url: "${DEFECT_DOJO_URL}"
operator:
  replicas: 1
  trivyDojoReportOperator:
    env:
      defectDojoActive: "true"
      defectDojoAutoCreateContext: "true"
      defectDojoCloseOldFindings: "false"
      defectDojoCloseOldFindingsProductScope: "false"
      defectDojoDeduplicationOnEngagement: "true"
      defectDojoMinimumSeverity: Info
      defectDojoProductTypeName: Research and Development
      defectDojoPushToJira: "false"
      defectDojoTestTitle: Kubernetes
      defectDojoVerified: "false"
      defectDojoEngagementName: "operator"
      defectDojoProductName: body["report"]["artifact"]["repository"]
      defectDojoEvalProductName: "true"
    image:
      repository: ghcr.io/telekom-mms/docker-trivy-dojo-operator
      tag: trivy-dojo-report-operator-0.3.3
```

I've added some additional debug logging for the raw and evaluated value of `DEFECT_DOJO_PRODUCT_NAME` 
which resulted into the following log output.

```sh
poetry run kopf run src/handlers.py --all-namespaces                 
[2023-11-14 15:29:06,767] settings             [INFO    ] Looking for resources with LABEL 'trivy-operator.resource.name' and LABEL_VALUE 'lol2'
[2023-11-14 15:29:06,775] kopf.activities.star [INFO    ] Activity 'configure' succeeded.
[2023-11-14 15:29:06,775] kopf._core.engines.a [INFO    ] Initial authentication has been initiated.
[2023-11-14 15:29:06,783] kopf.activities.auth [INFO    ] Activity 'login_via_client' succeeded.
[2023-11-14 15:29:06,783] kopf._core.engines.a [INFO    ] Initial authentication has finished.
[2023-11-14 15:29:33,326] kopf.objects         [INFO    ] [default/pod-lol2-lol2] Working on pod-lol2-lol2
body["report"]["artifact"]["repository"]
library/debian
```

@sjedlick can you give a shot again using additional single quotes for the complete value of `defectDojoProductName` ?

**Comment by rndmh3ro** [comment] 2023-11-14 16:56
problem was the re-using of variable-names. When I did this I already had a bad feeling about it but decided to do it anyway because of laziness. Fixed by https://github.com/telekom-mms/trivy-dojo-report-operator/commit/906650e6d23359f971ce1101f52d353ee98988d8

**Closed** 2023-11-14 16:57 UTC
Labels: bug
